module.exports = ['Restangular',
    function (Restangular) {
        var english = {
            "off": false,
            "maxVisitorInactiveMins": 4,
            "status": "online",
            "hideWhenOffline": false,
            "showAvatarPreChat": true,
            "showTeamAvatarPreChat": true,
            "newMsgNotifications": true,
            "activeAgentAvatar": "",
            "forwardSlackUserName": true,
            "titleColor": "#36bffd",
            "titleFontColor": "#fff",
            "onlineTitle": "Question? Chat with us.",
            "offlineTitle": "Leave a message",
            "agentLabel": "Callburn Team",
            "browserSideAuthorLabel": "Me",
            "onlineMessagePlaceholder": "Type message here…",
            "whiteLabel": false,
            "trackPresence": true,
            "offlineGreeting": "Sorry we are away, but we would love to hear from you and chat soon!",
            "offlineEmailPlaceholder": "Email",
            "offlineMessagePlaceholder": "Your message here",
            "offlineNamePlaceholder": "Name (optional but helpful)",
            "offlineSendButton": "Send",
            "offlineThankYouMessage": "Thanks for your message. We will be in touch soon!",
            "requireInfo": false,
            "requireInfoGreeting": "Enter your name and email to start chatting!",
            "requireInfoSubmitBtn": "Start",
            "requestScreenshotText": "Callburn would like to take a screenshot of your browser. Confirm below:",
            "requestScreenshotAllowLabel": "Take screenshot",
            "requestScreenshotDeclineLabel": "Decline",
            "teamAvatarOn": true,
            "collapsedMode": "chip",
            "defaultOkBtnLabel": "Ok",
            "defaultSendBtnLabel": "Send",
            "defaultCancelBtnLabel": "Cancel",
            "defaultYesBtnLabel": "Yes",
            "defaultNoBtnLabel": "No",
            "showConversationEnd": true,
            "showConversationRating": true,
            "conversationEndLabel": "Your chat session has ended. Thanks for chatting!",
            "conversationRatingLabel": "How would you rate Callburn service?",
            "conversationRatingThankYou": "Thanks for your feedback!",
            "conversationRatingPlaceholder": "How can we improve?",
            "conversationEndTranscriptPlaceholder": "Email to send transcript of chat",
            "conversationEndConfirmationQuestion": "Are you sure you want to end this chat?",
            "blacklistedUrls": "",
            "useSgmt": true,
            "autoResponseMessage": "Questions? Just type it below."
        };
        var italian = {
            "off": false,
            "maxVisitorInactiveMins": 4,
            "status": "online",
            "hideWhenOffline": false,
            "showAvatarPreChat": true,
            "showTeamAvatarPreChat": true,
            "newMsgNotifications": true,
            "activeAgentAvatar": "",
            "forwardSlackUserName": true,
            "titleColor": "#36bffd",
            "titleFontColor": "#fff",
            "onlineTitle": "Dubbi?  Chatta con il nostro team.",
            "offlineTitle": "Lascia un messaggio",
            "agentLabel": "Callburn Team",
            "browserSideAuthorLabel": "Io",
            "onlineMessagePlaceholder": "Scrivi un messaggio…",
            "whiteLabel": false,
            "trackPresence": true,
            "offlineGreeting": "Non siamo attualmente online, scrivi un messaggio e faremo tutto il possibile per risponderti velocemente!",
            "offlineEmailPlaceholder": "Email",
            "offlineMessagePlaceholder": "Il tuo messaggio",
            "offlineNamePlaceholder": "Nome (opzionale peró utile)",
            "offlineSendButton": "Invia",
            "offlineThankYouMessage": "Grazie per il tuo messaggio, risponderemo non appena possibile!",
            "requireInfo": false,
            "requireInfoGreeting": "Introduci il tuo nome e comincia a chattare con noi!",
            "requireInfoSubmitBtn": "Start",
            "requestScreenshotText": "Il supporto tecnico di Callburn richiede una istantanea del tuo schermo; confermi l'invio?",
            "requestScreenshotAllowLabel": "Invia istantanea",
            "requestScreenshotDeclineLabel": "Rifiuta",
            "teamAvatarOn": true,
            "collapsedMode": "chip",
            "defaultOkBtnLabel": "Ok",
            "defaultSendBtnLabel": "Invia",
            "defaultCancelBtnLabel": "Cancella",
            "defaultYesBtnLabel": "Si",
            "defaultNoBtnLabel": "No",
            "showConversationEnd": true,
            "showConversationRating": true,
            "conversationEndLabel": "Grazie per avere contattato con il nostro team!",
            "conversationRatingLabel": "Come valuteresti Callburn?",
            "conversationRatingThankYou": "Grazie per il tuo feedback!",
            "conversationRatingPlaceholder": "Come potremmo migliorare?",
            "conversationEndTranscriptPlaceholder": "Invia una mail con la trascrizione di questa chat",
            "conversationEndConfirmationQuestion": "Sei sicuro che vuoi terminare questa chat?",
            "blacklistedUrls": "",
            "useSgmt": true,
            "autoResponseMessage": "Domande? Siamo in linea e pronti a rispondere."
        };
        var spanish = {
            "off": false,
            "maxVisitorInactiveMins": 4,
            "status": "online",
            "hideWhenOffline": false,
            "showAvatarPreChat": true,
            "showTeamAvatarPreChat": true,
            "newMsgNotifications": true,
            "activeAgentAvatar": "",
            "forwardSlackUserName": true,
            "titleColor": "#36bffd",
            "titleFontColor": "#fff",
            "onlineTitle": "¿preguntas? Habla con nosotros.",
            "offlineTitle": "Deja un mensaje",
            "agentLabel": "Callburn Team",
            "browserSideAuthorLabel": "Yo",
            "onlineMessagePlaceholder": "Escribe un mensaje…",
            "whiteLabel": false,
            "trackPresence": true,
            "offlineGreeting": "No estamos conectados al momento, pero escríbenos y te contestaremos en cuanto nos sea possible!",
            "offlineEmailPlaceholder": "Email",
            "offlineMessagePlaceholder": "Tu mensaje",
            "offlineNamePlaceholder": "Nombre (opcional)",
            "offlineSendButton": "Envía",
            "offlineThankYouMessage": "Gracias por enviarnos tu mensaje, te contestaremos cuanto antes!",
            "requireInfo": false,
            "requireInfoGreeting": "Introduce tu nombre y empieza a hablar con nosotros!",
            "requireInfoSubmitBtn": "Empezar",
            "requestScreenshotText": "El soporte de Callburn quiere coger una captura de tu pantalla. ¿Confirmas?",
            "requestScreenshotAllowLabel": "Enviar captura",
            "requestScreenshotDeclineLabel": "Rechazar",
            "teamAvatarOn": true,
            "collapsedMode": "chip",
            "defaultOkBtnLabel": "Ok",
            "defaultSendBtnLabel": "Envía",
            "defaultCancelBtnLabel": "Borrar",
            "defaultYesBtnLabel": "Yes",
            "defaultNoBtnLabel": "No",
            "showConversationEnd": true,
            "showConversationRating": true,
            "conversationEndLabel": "Gracias por habernos contactado!",
            "conversationRatingLabel": "¿Como valorarías Callburn?",
            "conversationRatingThankYou": "Gracias por valorarnos!",
            "conversationRatingPlaceholder": "¿Como podemos mejorar?",
            "conversationEndTranscriptPlaceholder": "Envía una transcripción de la chat por correo electrónico",
            "conversationEndConfirmationQuestion": "Estas seguro que quieres terminar esta chat?",
            "blacklistedUrls": "",
            "useSgmt": true,
            "autoResponseMessage": "¿preguntas? Habla con nosotros, estamos conectados y listos para contestarte.."
        };
        return {
            language: function (lang) {
                switch (lang) {
                    case 'en':
                        return english;
                        break;
                    case 'it':
                        return italian;
                        break;
                    case 'es':
                        return spanish;
                        break;
                    default:
                        return english;
                        break;
                }
            }
        }
    }];